$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")

function Assert-FileExists {
    param([string]$Path)
    $fullPath = Join-Path $repoRoot $Path
    if (-not (Test-Path -LiteralPath $fullPath)) {
        throw "Missing expected file: $Path"
    }
}

function Assert-Contains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Description
    )

    $fullPath = Join-Path $repoRoot $Path
    $content = Get-Content -LiteralPath $fullPath -Raw
    if ($content -notmatch $Pattern) {
        throw "Missing $Description in $Path"
    }
}

function Assert-NotContains {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Description
    )

    $fullPath = Join-Path $repoRoot $Path
    $content = Get-Content -LiteralPath $fullPath -Raw
    if ($content -match $Pattern) {
        throw "Unexpected $Description in $Path"
    }
}

Assert-FileExists "Core/Inc/max30102.h"
Assert-FileExists "Core/Src/max30102.c"
Assert-FileExists "Core/Inc/max30102_service.h"
Assert-FileExists "Core/Src/max30102_service.c"
Assert-FileExists "Core/Inc/imu_sensor.h"
Assert-FileExists "Core/Src/imu_sensor.c"
Assert-FileExists "Core/Inc/walk_metrics.h"
Assert-FileExists "Core/Src/walk_metrics.c"
Assert-FileExists "Core/Inc/usart.h"
Assert-FileExists "Core/Src/usart.c"

Assert-Contains "CMakeLists.txt" "Core/Src/max30102\.c" "MAX30102 driver source"
Assert-Contains "CMakeLists.txt" "Core/Src/max30102_service\.c" "MAX30102 service source"
Assert-Contains "CMakeLists.txt" "Core/Src/imu_sensor\.c" "IMU sensor source"
Assert-Contains "CMakeLists.txt" "Core/Src/walk_metrics\.c" "walk metrics source"
Assert-Contains "CMakeLists.txt" "Core/Src/usart\.c" "USART wireless source"

Assert-Contains "Core/Inc/max30102.h" "MAX30102_I2C_ADDR_7BIT\s+0x57U" "7-bit MAX30102 I2C address"
Assert-Contains "Core/Inc/max30102.h" "MAX30102_EXPECTED_PART_ID\s+0x15U" "MAX30102 PART_ID"
Assert-Contains "Core/Inc/max30102.h" "typedef struct\s*\{[^}]*fifoWritePtr[^}]*fifoReadPtr[^}]*fifoAvailable[^}]*fifoConfig[^}]*modeConfig[^}]*spo2Config[^}]*led1Pa[^}]*led2Pa[^}]*interruptEnable1[^}]*interruptEnable2[^}]*overflowCounter[^}]*\}\s*Max30102Diagnostics;" "MAX30102 diagnostic register struct"
Assert-Contains "Core/Inc/max30102.h" "MAX30102_ReadDiagnostics" "MAX30102 diagnostic register reader"
Assert-Contains "Core/Inc/max30102.h" "MAX30102_ClearFifo" "MAX30102 FIFO clear helper"
Assert-Contains "Core/Inc/max30102.h" "MAX30102_KickSampleEngine" "MAX30102 sample engine kick helper"
Assert-Contains "Core/Inc/max30102.h" "typedef struct\s*\{[^}]*bool\s+max30102Ack;[^}]*uint8_t\s+deviceCount;[^}]*uint8_t\s+firstAddress;[^}]*uint8_t\s+readyStatus;[^}]*uint32_t\s+i2cError;[^}]*\}\s*Max30102BusProbe;" "MAX30102 I2C bus probe struct"
Assert-Contains "Core/Inc/max30102.h" "MAX30102_ProbeBus" "MAX30102 I2C bus probe reader"
Assert-Contains "Core/Src/max30102.c" "HAL_I2C_IsDeviceReady\(&hi2c1" "MAX30102 I2C1 readiness check"
Assert-Contains "Core/Src/max30102.c" "HAL_I2C_GetError\(&hi2c1\)" "MAX30102 I2C1 HAL error capture"
Assert-Contains "Core/Src/max30102.c" "for\s*\(uint8_t address = 0x08U; address <= 0x77U; \+\+address\)" "MAX30102 I2C bus scan"
Assert-Contains "Core/Src/max30102.c" "HAL_Delay\(100U\)" "F103-aligned MAX30102 reset settle delay"
Assert-Contains "Core/Src/max30102.c" "MAX30102_INTR_ENABLE_1,\s*0xC0U" "F103-aligned MAX30102 interrupt enable"
Assert-Contains "Core/Src/max30102.c" "MAX30102_FIFO_CONFIG,\s*0x4FU" "MAX30102 FIFO configuration"
Assert-Contains "Core/Src/max30102.c" "MAX30102_SPO2_CONFIG,\s*0x2AU" "MAX30102 SpO2 sample configuration"
Assert-Contains "Core/Src/max30102.c" "MAX30102_LED1_PA,\s*0x2FU" "MAX30102 LED1 current"
Assert-Contains "Core/Src/max30102.c" "MAX30102_LED2_PA,\s*0x2FU" "MAX30102 LED2 current"
Assert-Contains "Core/Src/max30102.c" "MAX30102_MODE_CONFIG,\s*0x03U" "MAX30102 SpO2 mode configuration"
Assert-Contains "Core/Src/max30102.c" "MAX30102_FIFO_CONFIG,\s*&snapshot\.fifoConfig" "MAX30102 FIFO config diagnostic read"
Assert-Contains "Core/Src/max30102.c" "MAX30102_INTR_ENABLE_1,\s*&snapshot\.interruptEnable1" "MAX30102 interrupt enable 1 diagnostic read"
Assert-Contains "Core/Src/max30102.c" "MAX30102_INTR_ENABLE_2,\s*&snapshot\.interruptEnable2" "MAX30102 interrupt enable 2 diagnostic read"
Assert-Contains "Core/Src/max30102.c" "MAX30102_OVF_COUNTER,\s*&snapshot\.overflowCounter" "MAX30102 overflow counter diagnostic read"
Assert-Contains "Core/Src/max30102.c" "MAX30102_ClearFifo" "MAX30102 FIFO clear helper implementation"
Assert-Contains "Core/Src/max30102.c" "MAX30102_KickSampleEngine" "MAX30102 sample engine kick helper implementation"
Assert-Contains "Core/Src/max30102.c" "MAX30102_WriteReg\(MAX30102_MODE_CONFIG,\s*0x03U\)" "MAX30102 sample engine mode re-kick"

Assert-Contains "Core/Inc/max30102_service.h" "bool\s+heartValid;" "heart validity flag"
Assert-Contains "Core/Inc/max30102_service.h" "bool\s+spo2Valid;" "SpO2 validity flag"
Assert-Contains "Core/Inc/max30102_service.h" "bool\s+beatPulse;" "beat pulse flag"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+signalQuality;" "signal quality field"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+fifoWritePtr;" "FIFO write pointer diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+fifoReadPtr;" "FIFO read pointer diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+fifoAvailable;" "FIFO available sample diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+modeConfig;" "mode config diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+spo2Config;" "SpO2 config diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+led1Pa;" "LED1 current diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+led2Pa;" "LED2 current diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+fifoConfig;" "FIFO config diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+interruptEnable1;" "interrupt enable 1 diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+interruptEnable2;" "interrupt enable 2 diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+overflowCounter;" "overflow counter diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+maxFifoAvailable;" "max FIFO depth diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint32_t\s+samplesReadTotal;" "sample read total diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint32_t\s+emptyFifoPolls;" "empty FIFO poll diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+sampleEngineTestCode;" "sample engine self-test result diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+sampleEngineFifoAfterKick;" "sample engine post-kick FIFO diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+sampleEngineReadCode;" "sample engine FIFO_DATA read result diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint32_t\s+sampleEngineRawRed;" "sample engine raw red diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint32_t\s+sampleEngineRawIr;" "sample engine raw IR diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint32_t\s+fifoReadAttempts;" "FIFO read attempt diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "bool\s+i2cReady;" "I2C ready diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "bool\s+max30102Ack;" "MAX30102 address ACK diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+busDeviceCount;" "I2C bus device count diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+busFirstAddress;" "I2C bus first address diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint8_t\s+i2cReadyStatus;" "I2C ready status diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint32_t\s+i2cError;" "I2C HAL error diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint16_t\s+fifoReadFailures;" "FIFO read failure diagnostic"
Assert-Contains "Core/Inc/max30102_service.h" "uint16_t\s+diagnosticReadFailures;" "diagnostic read failure counter"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_REQUIRED_SAMPLES\s+150U" "150-sample processing window"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_SAMPLE_THRESHOLD\s+100000U" "100000 raw sample finger threshold"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_FIFO_DEPTH\s+32U" "MAX30102 FIFO depth constant"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_SAMPLE_PERIOD_MS\s+20U" "20ms poll period"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_EFFECTIVE_SAMPLE_HZ\s+50U" "50Hz effective sampling rate"
Assert-Contains "Core/Src/max30102_service.c" "g_lastBeatIntervalMs" "F103-aligned beat interval state"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.heartBpm\s*=\s*g_lastStableHeartBpm;" "immediate heart result publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.heartValid\s*=\s*true;" "immediate heart validity publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.spo2X10\s*=\s*g_lastStableSpo2X10;" "immediate SpO2 result publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.spo2Valid\s*=\s*true;" "immediate SpO2 validity publication"
Assert-Contains "Core/Src/max30102_service.c" "quality_x1000" "F103-aligned signal quality scaling"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_ReadDiagnostics" "MAX30102 diagnostic register polling"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_ProbeBus" "MAX30102 I2C bus probe polling"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.i2cReady" "I2C ready publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.i2cError" "I2C error publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.fifoReadFailures" "FIFO read failure tracking"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.diagnosticReadFailures" "diagnostic read failure tracking"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.fifoConfig" "FIFO config publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.interruptEnable1" "interrupt enable 1 publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.interruptEnable2" "interrupt enable 2 publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.overflowCounter" "overflow counter publication"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.maxFifoAvailable" "max FIFO depth tracking"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.samplesReadTotal" "sample read total tracking"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.emptyFifoPolls" "empty FIFO poll tracking"
Assert-Contains "Core/Src/max30102_service.c" "Max30102Service_EffectiveFifoAvailable" "overflow-aware FIFO availability helper"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.fifoWritePtr\s*==\s*g_snapshot\.fifoReadPtr" "FIFO pointer wrap detection"
Assert-Contains "Core/Src/max30102_service.c" "g_overflowDrainPendingReset" "overflow drain reset tracking"
Assert-Contains "Core/Src/max30102_service.c" "Max30102Service_ResetAfterOverflowDrain" "post-overflow FIFO reset helper"
Assert-Contains "Core/Src/max30102_service.c" "available\s*=\s*MAX30102_SERVICE_FIFO_DEPTH" "overflowed FIFO drain depth"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_ClearFifo\(\)\s*\|\|\s*!MAX30102_KickSampleEngine\(\)" "post-overflow FIFO clear and sample-engine re-kick"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_SAMPLE_ENGINE_SETTLE_MS\s+150U" "150ms sample engine settle diagnostic"
Assert-Contains "Core/Src/max30102_service.c" "Max30102Service_RunSampleEngineSelfTest" "sample engine self-test routine"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.sampleEngineTestCode" "sample engine self-test result tracking"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.sampleEngineFifoAfterKick" "sample engine post-kick FIFO tracking"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_ENGINE_READ_NOT_RUN" "sample engine FIFO_DATA read not-run code"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_ENGINE_READ_OK" "sample engine FIFO_DATA read success code"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_SERVICE_ENGINE_READ_FAIL" "sample engine FIFO_DATA read failure code"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.sampleEngineReadCode" "sample engine FIFO_DATA read result tracking"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.sampleEngineRawRed" "sample engine raw red tracking"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.sampleEngineRawIr" "sample engine raw IR tracking"
Assert-Contains "Core/Src/max30102_service.c" "g_snapshot\.fifoReadAttempts" "FIFO read attempt tracking"
Assert-Contains "Core/Src/max30102_service.c" "Max30102Service_RecordSampleEngineRead" "sample engine FIFO_DATA read helper"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_ClearFifo" "sample engine self-test FIFO clear"
Assert-Contains "Core/Src/max30102_service.c" "MAX30102_KickSampleEngine" "sample engine self-test mode re-kick"
Assert-NotContains "Core/Src/max30102_service.c" "scope_debug" "F103 scope debug dependency"
Assert-NotContains "Core/Src/max30102_service.c" "HAL_UART" "UART debug dependency"

Assert-Contains "Core/Src/main.c" "max30102_service\.h" "MAX30102 service include"
Assert-Contains "Core/Src/main.c" "imu_sensor\.h" "IMU service include"
Assert-Contains "Core/Src/main.c" "usart\.h" "USART wireless include"
Assert-Contains "Core/Src/main.c" "MX_I2C1_Init\(\)" "I2C1 init call"
Assert-Contains "Core/Src/main.c" "MX_USART1_UART_Init\(\)" "USART1 wireless init call"
Assert-Contains "Core/Src/main.c" "IMU_Sensor_Init\(\)" "IMU sensor init call"
Assert-Contains "Core/Src/main.c" "Max30102Service_Init\(\)" "MAX30102 service init call"
Assert-Contains "Core/Src/main.c" "IMU_Sensor_Process\(\)" "IMU sensor process call"
Assert-Contains "Core/Src/main.c" "Max30102Service_Poll\(HAL_GetTick\(\)\)" "MAX30102 service poll call"
Assert-NotContains "Core/Src/main.c" "MX_I2C4_Init\(\)" "I2C4 init call"

Assert-Contains "Core/Src/i2c.c" "I2C_HandleTypeDef hi2c1" "I2C1 handle"
Assert-Contains "Core/Inc/i2c.h" "extern I2C_HandleTypeDef hi2c1" "I2C1 extern"
Assert-NotContains "Core/Inc/i2c.h" "hi2c4" "I2C4 handle declaration"
Assert-NotContains "Core/Inc/i2c.h" "MX_I2C4_Init" "I2C4 init declaration"
Assert-NotContains "Core/Src/i2c.c" "I2C_HandleTypeDef hi2c4" "I2C4 handle definition"
Assert-NotContains "Core/Src/i2c.c" "void MX_I2C4_Init" "I2C4 init implementation"
Assert-Contains "Core/Src/i2c.c" "PB8\s+-+> I2C1_SCL" "PB8 I2C1 SCL mapping"
Assert-Contains "Core/Src/i2c.c" "PB9\s+-+> I2C1_SDA" "PB9 I2C1 SDA mapping"
Assert-Contains "H750_TouchGFX.ioc" "PB8.Signal=I2C1_SCL" "PB8 .ioc I2C1 SCL mapping"
Assert-Contains "H750_TouchGFX.ioc" "PB9.Signal=I2C1_SDA" "PB9 .ioc I2C1 SDA mapping"
Assert-NotContains "H750_TouchGFX.ioc" "PB8.Signal=I2C4_SCL" "PB8 .ioc I2C4 SCL mapping"
Assert-NotContains "H750_TouchGFX.ioc" "PB9.Signal=I2C4_SDA" "PB9 .ioc I2C4 SDA mapping"
Assert-NotContains "H750_TouchGFX.ioc" "Mcu\.IP\d+=I2C4" "I2C4 peripheral registration"

Assert-Contains "Core/Src/imu_sensor.c" "IMU_ENABLE_I2C_FALLBACK\s+0U" "disabled IMU I2C fallback"
Assert-Contains "Core/Src/imu_sensor.c" "parse_wireless_sample" "IMU wireless sample parser"
Assert-Contains "Core/Src/imu_sensor.c" "IMU_Sensor_OnWirelessByte" "IMU wireless RX byte handler"
Assert-Contains "Core/Src/imu_sensor.c" "read_wireless_sample" "IMU wireless sample reader"
Assert-Contains "Core/Src/usart.c" "GPIO_PIN_9\s*\|\s*GPIO_PIN_10" "USART1 PA9/PA10 pin setup"
Assert-Contains "Core/Src/usart.c" "USART1_Wireless_IRQHandler" "USART1 wireless IRQ handler"
Assert-Contains "Core/Src/stm32h7xx_it.c" "USART1_IRQHandler" "USART1 interrupt vector"
Assert-Contains "Core/Src/stm32h7xx_it.c" "USART1_Wireless_IRQHandler" "USART1 interrupt forwarding"
Assert-Contains "Core/Src/walk_metrics.c" "WalkMetrics_Update" "walk metric update routine"
Assert-Contains "Core/Src/walk_metrics.c" "step_count\+\+" "walk step counter"

Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+spo2Percent;" "watch SpO2 field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint32_t\s+rawRed;" "watch raw red field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint32_t\s+rawIr;" "watch raw IR field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint16_t\s+validSamples;" "watch valid sample count field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+partId;" "watch part id field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+fifoWritePtr;" "watch FIFO write pointer field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+fifoReadPtr;" "watch FIFO read pointer field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+fifoAvailable;" "watch FIFO available field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+modeConfig;" "watch mode config field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+spo2Config;" "watch SpO2 config field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+led1Pa;" "watch LED1 current field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+led2Pa;" "watch LED2 current field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+fifoConfig;" "watch FIFO config field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+interruptEnable1;" "watch interrupt enable 1 field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+interruptEnable2;" "watch interrupt enable 2 field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+overflowCounter;" "watch overflow counter field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+maxFifoAvailable;" "watch max FIFO depth field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint32_t\s+samplesReadTotal;" "watch sample read total field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint32_t\s+emptyFifoPolls;" "watch empty FIFO poll field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+sampleEngineTestCode;" "watch sample engine self-test result field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+sampleEngineFifoAfterKick;" "watch sample engine post-kick FIFO field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+sampleEngineReadCode;" "watch sample engine FIFO_DATA read result field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint32_t\s+sampleEngineRawRed;" "watch sample engine raw red field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint32_t\s+sampleEngineRawIr;" "watch sample engine raw IR field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint32_t\s+fifoReadAttempts;" "watch FIFO read attempt field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "bool\s+i2cReady;" "watch I2C ready field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "bool\s+max30102Ack;" "watch MAX30102 ACK field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+busDeviceCount;" "watch I2C bus device count field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+busFirstAddress;" "watch I2C first address field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint8_t\s+i2cReadyStatus;" "watch I2C ready status field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint32_t\s+i2cError;" "watch I2C error field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint16_t\s+fifoReadFailures;" "watch FIFO read failures field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "uint16_t\s+diagnosticReadFailures;" "watch diagnostic read failures field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "bool\s+sensorReady;" "watch sensor ready field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "bool\s+fingerDetected;" "watch finger detected field"
Assert-Contains "TouchGFX/gui/include/gui/watch/WatchUiData.hpp" "bool\s+sensorValid;" "watch sensor validity field"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "#ifndef SIMULATOR" "simulator guard around MAX30102 service"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "Max30102Service_GetSnapshot" "TouchGFX model snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.rawRed\s*=\s*sensor\.rawRed;" "raw red snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.rawIr\s*=\s*sensor\.rawIr;" "raw IR snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.validSamples\s*=\s*sensor\.validSamples;" "valid sample count snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.partId\s*=\s*sensor\.partId;" "part id snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.fifoWritePtr\s*=\s*sensor\.fifoWritePtr;" "FIFO write pointer snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.fifoReadPtr\s*=\s*sensor\.fifoReadPtr;" "FIFO read pointer snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.fifoAvailable\s*=\s*sensor\.fifoAvailable;" "FIFO available snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.modeConfig\s*=\s*sensor\.modeConfig;" "mode config snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.spo2Config\s*=\s*sensor\.spo2Config;" "SpO2 config snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.led1Pa\s*=\s*sensor\.led1Pa;" "LED1 current snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.led2Pa\s*=\s*sensor\.led2Pa;" "LED2 current snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.fifoConfig\s*=\s*sensor\.fifoConfig;" "FIFO config snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.interruptEnable1\s*=\s*sensor\.interruptEnable1;" "interrupt enable 1 snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.interruptEnable2\s*=\s*sensor\.interruptEnable2;" "interrupt enable 2 snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.overflowCounter\s*=\s*sensor\.overflowCounter;" "overflow counter snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.maxFifoAvailable\s*=\s*sensor\.maxFifoAvailable;" "max FIFO depth snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.samplesReadTotal\s*=\s*sensor\.samplesReadTotal;" "sample read total snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.emptyFifoPolls\s*=\s*sensor\.emptyFifoPolls;" "empty FIFO poll snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.sampleEngineTestCode\s*=\s*sensor\.sampleEngineTestCode;" "sample engine self-test result snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.sampleEngineFifoAfterKick\s*=\s*sensor\.sampleEngineFifoAfterKick;" "sample engine post-kick FIFO snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.sampleEngineReadCode\s*=\s*sensor\.sampleEngineReadCode;" "sample engine FIFO_DATA read result snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.sampleEngineRawRed\s*=\s*sensor\.sampleEngineRawRed;" "sample engine raw red snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.sampleEngineRawIr\s*=\s*sensor\.sampleEngineRawIr;" "sample engine raw IR snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.fifoReadAttempts\s*=\s*sensor\.fifoReadAttempts;" "FIFO read attempt snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.i2cReady\s*=\s*sensor\.i2cReady;" "I2C ready snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.max30102Ack\s*=\s*sensor\.max30102Ack;" "MAX30102 ACK snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.busDeviceCount\s*=\s*sensor\.busDeviceCount;" "I2C bus device count snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.busFirstAddress\s*=\s*sensor\.busFirstAddress;" "I2C first address snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.i2cReadyStatus\s*=\s*sensor\.i2cReadyStatus;" "I2C ready status snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.i2cError\s*=\s*sensor\.i2cError;" "I2C error snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.fifoReadFailures\s*=\s*sensor\.fifoReadFailures;" "FIFO read failure snapshot bridge"
Assert-Contains "TouchGFX/gui/src/model/Model.cpp" "snapshot\.diagnosticReadFailures\s*=\s*sensor\.diagnosticReadFailures;" "diagnostic read failure snapshot bridge"
Assert-Contains "TouchGFX/gui/src/screen1_screen/screen1View.cpp" "gotowalkScreenNoTransition" "navigation to walk page"
Assert-Contains "TouchGFX/gui/src/screen1_screen/screen1View.cpp" "gotorunScreenNoTransition" "navigation to run page"
Assert-Contains "TouchGFX/gui/src/screen1_screen/screen1View.cpp" "gotoropeScreenNoTransition" "navigation to rope page"

foreach ($screen in @("walk", "run", "rope")) {
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "PLACE FINGER" "$screen no-finger display"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "SENSOR ERR" "$screen missing sensor display"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "MEASURING" "$screen collecting display"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "HR %u" "$screen heart rate value formatting"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "%u%%" "$screen SpO2 value formatting"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """TIME""" "$screen original time label"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """SPO2""" "$screen original SpO2 label"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """NOW""" "$screen original current metric label"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """AVG""" "$screen original average metric label"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "lastSnapshot\.sensorReady" "$screen sensor-ready state"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "lastSnapshot\.fingerDetected" "$screen finger-detected state"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "lastSnapshot\.sensorValid" "$screen sensor-valid state"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "lastSnapshot\.heartRate" "$screen heart rate value"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "lastSnapshot\.spo2Percent" "$screen SpO2 value"
    Assert-NotContains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """RED""" "$screen visible raw red diagnostic label"
    Assert-NotContains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """IR""" "$screen visible raw IR diagnostic label"
    Assert-NotContains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """FIFO""" "$screen visible FIFO diagnostic label"
    Assert-NotContains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """ID/M/S""" "$screen visible register diagnostic label"
    Assert-NotContains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" """A/F""" "$screen visible ACK/failure diagnostic label"
    Assert-NotContains "TouchGFX/gui/src/$($screen)_screen/$($screen)View.cpp" "CNT" "$screen visible sample counter diagnostic label"
    Assert-Contains "TouchGFX/gui/src/$($screen)_screen/$($screen)Presenter.cpp" "watchDataUpdated" "$screen presenter watch data forwarding"
}

Assert-Contains "TouchGFX/gui/src/walk_screen/walkView.cpp" """STEP""" "walk original step label"
Assert-Contains "TouchGFX/gui/src/walk_screen/walkView.cpp" "IMU_Sensor_Read" "walk page IMU sample read"
Assert-Contains "TouchGFX/gui/src/walk_screen/walkView.cpp" "WalkMetrics_Update" "walk page walk metric update"
Assert-Contains "TouchGFX/gui/src/walk_screen/walkView.cpp" "applyWalkMetricsOutput" "walk page metric display refresh"
Assert-Contains "TouchGFX/gui/src/run_screen/runView.cpp" """CAD""" "run original cadence label"
Assert-Contains "TouchGFX/gui/src/rope_screen/ropeView.cpp" """KCAL""" "rope original calorie label"

Write-Host "MAX30102 integration guard passed."
